<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RealDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('skill_categories')->insert([
            ['id' => 1, 'name' => '🔧 Back-End & Database', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => '🎨 Front-End Development', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => '🧰 Workflow & Dev Tools', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => '📦 WordPress & CMS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => '💬 Soft Skills', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => '🌀 Interests', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('skills')->insert([
            ['name' => 'PHP (OOP, MVC, basic Laravel)', 'skill_category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MySQL, PostgreSQL, REST API', 'skill_category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'HTML5, CSS3, JavaScript, jQuery, Alpine.js', 'skill_category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tailwind CSS, Bootstrap, Sass', 'skill_category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Git, GitHub, Docker, Composer, NPM', 'skill_category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jira, basic CI/CD understanding', 'skill_category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'WordPress, WooCommerce', 'skill_category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Custom themes & plugin development', 'skill_category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Analytical thinking', 'skill_category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Independence & problem-solving', 'skill_category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kitesurfing coaching & freestyle', 'skill_category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Teamwork and communication', 'skill_category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Basic unit testing with PhpUnit / Pest', 'skill_category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Debugging, performance, and security (XSS, CSRF, SQL Injection)', 'skill_category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Responsive Web Design (RWD)', 'skill_category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Accessibility & WCAG standards', 'skill_category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'PHP version upgrades, dev environments, migrations', 'skill_category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oxygen Builder, Elementor', 'skill_category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Advanced Custom Fields (ACF), CPT, WP REST API', 'skill_category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Attention to visual detail & clean UI', 'skill_category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Curious & always learning new tech', 'skill_category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Music production', 'skill_category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Graphic design', 'skill_category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Reiki & mindfulness practices', 'skill_category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('projects')->insert([
            [
                'developer_id' => 1,
                'title' => 'NextStep Collective',
                'description' => 'Job board build with Laravel',
                'company' => 'KaroCreative',
                'location' => 'Remote',
                'image' => 'https://karocreative.pl/wp-content/uploads/2025/05/ns_collective_screen-scaled.webp',
                'image_alt' => 'screenshot next step collective',
                'featured' => true,
                'url_github' => 'https://github.com/g-i-kala/laravel-nextstep-collective',
                'url_demo' => 'https://nextstep-collective-main-groblg.laravel.cloud',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
               'developer_id' => 1,
               'title' => 'Fitness Pleasure',
               'description' => 'Customizable Wordpress theme with full responsiveness and SEO optimization.',
               'company' => 'Fitness Co.',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2025/03/fitness_pleasure-scaled.webp',
               'image_alt' => 'screenshot fitness pleasure',
               'featured' => true,
               'url_github' => 'https://github.com/g-i-kala/wp-custom-theme-fitness-pleasure',
               'url_demo' => 'https://srv48890.seohost.com.pl/fitness-pleasure/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'Kalissima',
               'description' => 'Simple blog Wordpress custom theme with custom header and footer options.',
               'company' => 'Kalissima',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2025/02/screenshot-scaled.jpg',
               'image_alt' => 'screenshot',
               'featured' => true,
               'url_github' => 'https://github.com/g-i-kala/wp-custom-themes/tree/ed542916dbc733b3de5cb0c10e73629fc243a46d/kalissima',
               'url_demo' => 'https://srv48890.seohost.com.pl/kalissima/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => '#dajse streetwear',
               'description' => 'Work in progress with custom UX/UI design and Woocommerce integration.',
               'company' => 'Dajse',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2025/02/dajse_screenshot-scaled.webp',
               'image_alt' => 'dajse screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://karocreative.pl/dajse/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'reikiflow.pl',
               'description' => 'Graphic design & logo design with custom snippets and booking calendar integration.',
               'company' => 'Reiki Flow',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2024/09/reik.png',
               'image_alt' => 'page screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://reikiflow.pl/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'joannaduda.eu',
               'description' => 'Graphic design & logo design with SEO optimization.',
               'company' => 'Joanna Duda',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2024/09/jinx.png',
               'image_alt' => 'page screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://joannaduda.eu/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'letgotohaveit.com',
               'description' => 'Graphic design & logo design with WooCommerce integration.',
               'company' => 'LetGoToHaveIt',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2024/09/lgth.png',
               'image_alt' => 'page screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://letgotohaveit.com/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'kdp books listing',
               'description' => 'Minimalistic graphic design with ACF integration.',
               'company' => 'KDP Books',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2025/02/kdp_books-scaled.webp',
               'image_alt' => 'page screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://karocreative.pl/books/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'kalafonia.com',
               'description' => 'Graphic design & logo design with SEO optimization.',
               'company' => 'Kalafonia',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2024/09/kf.png',
               'image_alt' => 'page screenshot',
               'featured' => false,
               'url_github' => null,
               'url_demo' => 'https://karocreative.pl/kalafonia/',
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'developer_id' => 1,
               'title' => 'karocreative - react build 2023',
               'description' => 'Graphic design & logo design implemented using React.',
               'company' => 'KaroCreative',
               'location' => 'Remote',
               'image' => 'https://karocreative.pl/wp-content/uploads/2025/01/tb_react_portfolio.png',
               'image_alt' => 'website thumbnail',
               'featured' => false,
               'url_github' => 'https://github.com/g-i-kala/karocreative.pl-react-version',
               'url_demo' => 'https://karocreative.pl/react-portfolio-kc',
               'created_at' => now(),
               'updated_at' => now(),
           ],
        ]);
    }
}
